### ISSUE TITLE
Doesn't work with the desktop version Safari

### ISSUE THREAD

**Issue by ghost** [ElJere/aCompas#7]
- If the app can work with the desktop version of Safari, make it work
- Otherwise, detect Safari and display a warning popin like with iOS

**Comment by ElJere** [comment]
Pour Safari, la console ne me donne rien de très utile : un "unexpected 
CSS token" sur la css de Bootstrap, je pense que ce n'est pas ça...

Par contre, le bug se produit sur la fonction qui lance la visualisation 
svg. Pas sur la génération et la lecture du rythme, qui se déroulent 
bien. Il semble que le svg ne se vide pas avant de dessiner le nouveau 
quand on change de palo.

**Comment by ghost** [comment]
Can you update your code and try again (or try on http://acompas.audio - I updated the production website) ?
In 418d87d15e81a5e9db3cd7f7b5f9dc1f5e2ce0a3, I empty the visualization's &lt;svg&gt; using the raphael.js API instead of jQuery. In looks exactly like the issues I had with jQuery + &lt;svg&gt; ....

Try again and tell me if it works better.

**Comment by ElJere** [comment]
Solved !
